In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("data/Merged Colorectal Cancer Patient Data.csv", sep=",")
df

ID_REF  Age (in years) Dukes Stage  Gender Location  DFS (in months)  \
0   GSM877126            62.0           A    Male     Left            108.0   
1   GSM877127            77.0           B    Male     Left             40.0   
2   GSM877128            66.0           C  Female     Left             49.0   
3   GSM877129            72.0           D  Female     Left             45.0   
4   GSM877130            75.0           C    Male     Left             40.0   
..        ...             ...         ...     ...      ...              ...   
57  GSM877184            54.0           C    Male     Left             22.0   
58  GSM877185            48.0           D    Male    Right             64.0   
59  GSM877186            65.0           C    Male     Left             25.0   
60  GSM877187            71.0           A    Male   Rectum             58.0   
61  GSM877188            57.0           A    Male   Rectum             68.0   

    DFS event  Adj_Radio  Adj_Chem    117_at  ...  1554911_at  1554912_at  \
0         0.0        1.0       0.0  6.029834  ...    3.504809    2.856109   
1         1.0        1.0       0.0  6.344321  ...    3.957833    2.988643   
2         0.0        1.0       0.0  5.023127  ...    3.749518    2.610840   
3         0.0        1.0       1.0  4.612727  ...    3.610429    2.728274   
4         0.0        0.0       1.0  5.865944  ...    3.520434    2.664744   
..        ...        ...       ...       ...  ...         ...         ...   
57        1.0        0.0       0.0  4.835558  ...    3.637413    2.787781   
58        0.0        1.0       0.0  5.694010  ...    3.733335    3.473473   
59        1.0        1.0       0.0  8.661629  ...    3.436002    2.706722   
60        1.0        1.0       0.0  5.702601  ...    3.438260    2.539084   
61        1.0        0.0       0.0  4.500368  ...    3.886770    2.796490   

    1554914_at  1554915_a_at  1554916_a_at  1554918_a_at  1554919_s_at  \
0     3.130712      5.603126      3.091348      4.009692      4.350400   
1     3.484177      6.601744      3.141737      4.679732      4.508760   
2     3.406207      6.003205      3.469987      4.781843      4.435054   
3     3.534871      5.858326      3.372291      3.653575      5.014994   
4     3.314746      5.388115      3.322147      4.666360      5.013006   
..         ...           ...           ...           ...           ...   
57    3.519436      6.026848      3.404074      4.103411      4.303329   
58    3.237316      6.167214      3.452096      4.724017      4.470426   
59    3.349033      6.238026      3.109042      6.897634      3.797626   
60    3.334590      5.842051      3.496104      4.883845      4.661893   
61    3.368317      6.165133      3.279520      4.328188      4.682695   

    1554920_at  213418_at  1554921_a_at  
0     2.512026   7.494499      4.030978  
1     2.427697   8.156995      2.827090  
2     2.531300   6.058687      2.930454  
3     2.608755   5.488072      2.949848  
4     2.657130   7.410725      3.054697  
..         ...        ...           ...  
57    2.422700   6.072618      2.853109  
58    2.634358   7.175365      2.667533  
59    2.756086  10.121831      2.971542  
60    2.581452   7.232090      2.719928  
61    2.529767   5.566607      2.860795  

[62 rows x 1944 columns]

In [3]:
from CMIM import cmim

In [7]:
df.columns

Index(['ID_REF', 'Age (in years)', 'Dukes Stage', 'Gender', 'Location',
       'DFS (in months)', 'DFS event', 'Adj_Radio', 'Adj_Chem', '117_at',
       ...
       '1554911_at', '1554912_at', '1554914_at', '1554915_a_at',
       '1554916_a_at', '1554918_a_at', '1554919_s_at', '1554920_at',
       '213418_at', '1554921_a_at'],
      dtype='object', length=1944)

In [16]:
X = df[['Age (in years)', 'Adj_Radio', '117_at','1554911_at']]
Y = df["DFS event"]

features_indices, objective_value, mutual_information = cmim(X, Y)
out = [features_indices, objective_value, mutual_information ]
# This is done to remove the trailing reduntant value.
features_indices.pop()
objective_value.pop()
mutual_information.pop()
# df[['Age (in years)', 'Adj_Radio']].shape
# X.to_numpy()

[array([2, 1, 0, 3, 3], dtype=int64),
 array([ 9.72806322e-01,  2.22044605e-16,  1.11022302e-16,  1.11022302e-16,
        -1.00000000e+12]),
 array([0.97280632, 0.0229402 , 0.56135834, 0.97280632, 0.97280632])]

In [15]:
def get_subset(features_index, mutual_information, threshold=0.53):
    merged = zip(features_index, mutual_information)
    sorted_features = sorted(merged, key=lambda x: x[1], reverse=True)

    filtered_features = filter(lambda x: x[1] > threshold, sorted_features)
    return filtered_features


# filter is a generator so we must run a loop to check
for i in get_subset(
    features_index=[1,0,0], 
    mutual_information=[3,7,8],
    threshold=3
):
    print(i)


(0, 8)
(0, 7)


array([[1., 2., 3.],
       [4., 5., 7.]])

In [6]:
arr[:, 1]

array([2., 5.])